{
 "title": "Health Stats",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "title": "Recent Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device Battery Level",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Battery remaining",
     "measurement": "DeviceBatteryLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "BPM" } },
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RHR",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "RestingHR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly Steps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Steps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"Steps_Intraday\" WHERE $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Steps",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Steps_Intraday",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spo2 Today",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "SpO2 Intraday",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SPO2_Intraday",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SpO2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "SpO2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "SPO2",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Pattern",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 24 },
   "targets": [
    {
     "alias": "Sleep levels",
     "measurement": "Sleep Levels",
     "query": "SELECT sleep_type FROM sleep_levels WHERE short = false",
     "select": [
      [
       { "params": [ "level" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "isMainSleep", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Last Day Total Sleep",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Total Asleep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "select": [
      [
       { "params": [ "minutesAsleep" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Pattern",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 28 },
   "targets": [
    {
     "alias": "Sleep levels",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Sleep Levels",
     "query": "SELECT sleep_type FROM sleep_levels WHERE short = false",
     "select": [
      [
       { "params": [ "level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "isMainSleep", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  { "title": "Sleep Data - Long Term", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Sleep",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesDeep" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesLight" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesREM" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesAwake" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Efficiency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Efficiency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "efficiency" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Relative Skin Temperature",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Relative Skin Temp ",
     "measurement": "Skin Temperature Variation",
     "select": [
      [
       { "params": [ "RelativeValue" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Sleep trends",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesDeep" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesLight" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesREM" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sleep Summary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutesAwake" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Regularity",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "alias": "Sleep Regularity",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "Sleep Levels",
     "query": "SELECT median(\"level\") FROM \"Sleep Levels\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "level" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Other Long Term Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Resting HR",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Resting HR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RestingHR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HRV",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "DailyRmssd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HRV",
     "select": [
      [
       { "params": [ "dailyRmssd" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spo2 ( Avg )",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "SpO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SPO2",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Breathing Rate",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Breathing Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BreathingRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly walk heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Hourly walk heatmap",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Steps_Intraday",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measurement": "Total Steps",
     "query": "SELECT sum(\"value\") FROM \"Steps\" WHERE $timeFilter GROUP BY time(1d, ) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Light Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesLightlyActive" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Fair Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesFairlyActive" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Intense Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesVeryActive" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HR Zones",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Fat Burn",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HR zones",
     "select": [
      [
       { "params": [ "Fat Burn" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Cardio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HR zones",
     "select": [
      [
       { "params": [ "Cardio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HR zones",
     "select": [
      [
       { "params": [ "Peak" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Activity over given duration",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 1, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Light Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesLightlyActive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Intense Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesVeryActive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Fair Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesFairlyActive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Sedentary",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Activity Minutes",
     "select": [
      [
       { "params": [ "minutesSedentary" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "alias": "Total Distance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "distance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Calories",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Total Calories",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "calories",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Band wearing ",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": " ",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "HeartRate_Intraday",
     "query": "SELECT mean(value) FROM \"heartrate\" WHERE $timeFilter GROUP BY time(2m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recent Activity",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Walk",
     "measurement": "Activity Records",
     "query": "SELECT \"calories\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') ",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivityName", "operator": "=", "value": "Walk" }
     ]
    },
    {
     "alias": "Swimming",
     "measurement": "Activity Records",
     "query": "SELECT \"calories\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') ",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivityName", "operator": "=", "value": "Swim" }
     ]
    },
    {
     "alias": "Biking",
     "measurement": "Activity Records",
     "query": "SELECT \"calories\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') ",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivityName", "operator": "=", "value": "Outdoor Bike" }
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Battery Percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceBatteryLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  }
 ]
}